name: SVG Combiner

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    combine:
        runs-on: ubuntu-latest
        if: github.actor != 'Candis Bot' # change 'Candis Bot' to the actual GitHub username of the bot

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0 # ensure all history is fetched
                  token: ${{ secrets.MY_PAT }}

            - name: Checkout SVG combiner script from main branch
              run: |
                  git fetch origin main
                  git checkout origin/main -- svg_combiner.py

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Combine SVGs
              run: |
                  pip install beautifulsoup4 lxml
                  python svg_combiner.py

            - name: Squash commits, commit and push
              run: |
                  git config --local user.email "devtools+candisbot@candis.io"
                  git config --local user.name "Candis Bot"
                  git checkout -b temp_branch
                  git add .
                  git commit -m "WIP"
                  git checkout ${{ github.head_ref }}
                  git reset --soft temp_branch
                  git status --porcelain | grep '^ M' && git commit -m "feat(icons): Updating icon set" || git commit -m "No changes to commit"
                  git push origin ${{ github.head_ref }}
