name: SVG Combiner

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    combine:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.MY_PAT }}

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Combine SVGs
              run: |
                  pip install beautifulsoup4 lxml
                  python svg_combiner.py  # or whatever you named your Python script

            - name: Commit and push
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add spritemap.tsx
                  git commit -m "Combine SVGs into spritemap.tsx" -a || echo "No changes to commit"
                  git push
