name: SVG Combiner

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    combine:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
                  token: ${{ secrets.MY_PAT }}

            - name: Checkout SVG combiner script from main branch
              run: |
                  git fetch origin main
                  git checkout origin/main -- svg_combiner.py

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Combine SVGs
              run: |
                  pip install beautifulsoup4 lxml
                  python svg_combiner.py

            - name: Commit and push
              run: |
                  git config --local user.email "devtools+candisbot@candis.io"
                  git config --local user.name "Candis Bot"
                  git add spritemap.tsx
                  FILE_CHANGE_COUNT=$(git diff --name-only HEAD~1 | wc -l)
                  if [ $FILE_CHANGE_COUNT -gt 0 ]
                  then
                      git commit --amend --no-edit # Combines all commits
                      git push origin +${{ github.head_ref }} # Force pushes the combined commit
                  else
                      echo "No changes to commit"
                  fi
